import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import LadyAudioPlayer from "@/components/LadyAudioPlayer";
import Footer from "@/components/Footer";
const Josefine = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Josefine.className} dark`}>
        <LadyAudioPlayer />
        {children}
        <Footer />
        </body>
    </html>
  );
}
